services:
  app:
    environment:
      - APP_NAME=poc-laravel-prod
      - APP_ENV=production
      - APP_DEBUG=false
    build:
      context: .
      dockerfile: Dockerfile
    image: poc-laravel
    container_name: poc-laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - poc-network

  nginx:
    image: nginx:alpine
    container_name: poc-laravel-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - poc-network
    depends_on:
      - app

networks:
  poc-network:
    driver: bridge
