name: Lighthouse Performance Monitoring

on:
  schedule:
    # - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheck
      with:
        urls: 'https://www.google.com'
        gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
        device: 'desktop'
    - name: Verify Lighthouse Check results
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "70"
        minBestPracticesScore: "70"
        minPerformanceScore: "50"
        minSeoScore: "70"